version: '3.7'
services:
    kafkaServer:
        image: apache/kafka:latest
        hostname: kafkaServer
        container_name: kafkaServer
        ports:
        - '9092:9092'
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://kafkaServer:9092,PLAINTEXT://kafkaServer:19092'
            KAFKA_PROCESS_ROLES: 'broker,controller'
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafkaServer:29093'
            KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
            CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'  
    topics:
        image: apache/kafka:latest
        command: > 
            bash -c "
            /opt/kafka/bin/kafka-topics.sh --create --topic fluentd_access_log --bootstrap-server kafkaServer:9092 
            && /opt/kafka/bin/kafka-topics.sh --create --topic flume_access_log --bootstrap-server kafkaServer:9092 
            && /opt/kafka/bin/kafka-topics.sh --create --topic logstash_access_log --bootstrap-server kafkaServer:9092"
        depends_on:
        - kafkaServer
    nginx:
        image: tap:nginx
        ports:
            - "80:80"
        volumes:
        - ngnix_logs:/var/log/nginx
        depends_on:
        - kafkaServer 
    flume:
        depends_on:
            - nginx
        image: tap:flume
        environment:
           FLUME_CONF_FILE: nginx.conf
        volumes:
            - ngnix_logs:/var/log/nginx
    fluentd:
        depends_on:
            - nginx
        image: tap:fluentd
        command: "-c /fluentd/etc/nginx.conf"
        volumes:
            - ngnix_logs:/var/log/nginx
            - ./fluentd/conf:/fluentd/etc/
    logstash:
        depends_on:
            - nginx
        image: tap:logstash
        environment:
            XPACK_MONITORING_ENABLED: "false"
        volumes:
            - ngnix_logs:/var/log/nginx
            - ./logstash/pipeline/nginx.conf:/usr/share/logstash/pipeline/logstash.conf
volumes:
    ngnix_logs:
networks:
    tap2:
        name: tap2
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.101.0/24


#     export KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"